language: cpp

sudo: required
dist: trusty
group: deprecated-2017Q4

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -q update
      install:
        - sudo apt-get -y install g++-5
        - sudo apt-get -y install libboost-all-dev
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=g++-5 .. && make && ./rhubarb/runTests
        - ls **/rhubarb-lip-sync-*.zip
    - os: osx
      osx_image: xcode7.3
      script:
        - mkdir build
        - cd build
        - cmake .. && make && ./rhubarb/runTests
        - ls **/rhubarb-lip-sync-*.zip
deploy:
  # Deploy to GitHub releases
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: "./rhubarb/rhubarb-lip-sync-*.zip"
  skip_cleanup: true
  on:
    tags: true
  tag_name: $TRAVIS_TAG
  draft: true
